### ISSUE TITLE
Bags will not stay separated- keep returning to merged/Never break bags

### ISSUE THREAD

**Issue by galapogosian** [Jaliborc/Bagnon#1834] opened 2023-12-24 20:28 UTC
**Which software were you running?**
 - Addon version name: Bagnon 10.2.7
 - Client used: Retail 10.2.0.52649

**Have you read the changelog?**
Yes

**Please describe the bug.**
Bags will not stay separated

**Please describe how to reproduce it.**
1. Go to 'Options'
2. Click on 'Bag break'
3. Scroll down to 'Always'

**Any Screenshots?**
N/A

**Error Logs are Important!**
No error message

**Comment by kennnygeee** [comment] 2023-12-25 06:26
Having the same issue on both 10.2.5 and 10.2.7 releases.

**Comment by Fl1pp3d0ff** [comment] 2023-12-25 21:50
Same difficulty here. In fact, I deleted ALL addons manually to see if it was an addon interaction (Scrap comes back with an error on login if it's installed at the same time as Bagnon).

Oddly, this behavior started at the same time Altoholic decided it wasn't going to show all the realms I've got toons on.. Unsure if that's related, BUT, as I stated, bag split does not stay set, even if Bagnon is the ONLY addon installed.

**Comment by darodriguesPT** [comment] 2023-12-25 22:11
Same here, but in my case, I've downgraded to 10.2.6, and it's ok there.

**Comment by Shauren** [comment] 2023-12-27 17:44
Probably `Added ability to break bags by type` from 10.2.7 broke this

**Comment by divmehz** [comment] 2023-12-28 03:38
same issue here, was infuriating me thinking i hadnt set it on all toons, but turns out i have it just doesnt retain the setting.

**Comment by barbd7** [comment] 2023-12-28 08:28
I too have been afflicted with this issue... I tried making character specific profiles and that didn't work either. If I change the settings they stay until I log out, then they immediately revert to one bag with no bag breaks on the same character or any other character I log into. Also happens for bank as well as inventory, not too sure about void storage or guild bank as I have never intentionally asked for any sort of bag breaks for those windows.
I would greatly appreciate the info on how to downgrade to 10.2.6, (if this will not be resolved anytime soon) as I can not find instructions online and I am not a computer wizard like so many folks out here who play lots of games. :S 
Thank you in advance :)

**Comment by ErikSlump** [comment] 2023-12-29 12:24
Confirmed. Issue is in 10.2.7 and 2.10.8. Downgraded to 2.10.6 and that works fine.

**Comment by galapogosian** [comment] 2023-12-29 16:18
Thank you. Very helpful.

**Comment by Jaliborc** [comment] 2023-12-29 19:49
Fixed internally

**Closed by Jaliborc** 2023-12-29 19:49 UTC

**Comment by Fl1pp3d0ff** [comment] 2023-12-29 22:34
When will the fixed version be released to Curse?
