### ISSUE TITLE
Bank doesn't update when withdrawing or depositing

### ISSUE THREAD

**Issue by Eviloverlord1989** [Jaliborc/Bagnon#655] opened 2018-01-22 14:50 UTC
When I move items from bank to bags or vice versa, the bank window doesnt update. Item icon stays in the bank when withdrawing or no icon appears when depositing. Can however still interact with whatever item I deposited if I know where it was deposited to.

Happening both on Azjol-Nerub and Kilrogg.

**Comment by Eviloverlord1989** [comment] 2018-01-22 23:48
Ok sometimes it works, sometimes not...

**Comment by Voxxel** [comment] 2018-02-01 08:16
I have the same issue with 7.3.9.. I got this bug everytime.

**Comment by Eviloverlord1989** [comment] 2018-02-03 09:22
Date: 2018-02-03 10:20:32
ID: 1
Error occured in: Global
Count: 1
Message: ...AddOns\Bagnon\external\Wildpants\components\item.lua line 335:
   attempt to compare number with string
Debug:
   [C]: ?
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:335: UpdateBorder()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:363: UpdateSearch()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:239: ?()
   ...AddOns\Bagnon\external\Wildpants\components\item.lua:477:
      ...AddOns\Bagnon\external\Wildpants\components\item.lua:475
Locals:

AddOns:
 (all my addons)
  BlizRuntimeLib_enUS v7.3.5.70300 <none>
  (ck=6ff)

Might be related to this error that i get at the start of a play session if I open my bank window from the inventory Bag Slots icon.

**Comment by AlexL1118** [comment] 2018-02-05 00:01
I have the same issue.

I wanted to help by describing actions to reproducing the problem, but it appears that I can't describe it: sometimes it happens, and sometimes not. Maybe it's enough to just reload UI to toggle its reproducibility, and I mean - to toggle in a random direction: it can exist before reload, and disappear after; or opposite - appear only after reload, even though it did not exist before reloading UI.

What is (probably) no doubt - is that v7.3.2 seems to work stable without such problem.

**Comment by AlexL1118** [comment] 2018-02-09 17:07
Question to the author(s)/supporter(s): Is there anything I can help you to debug this problem?

**Comment by reflexwolf** [comment] 2018-02-24 16:58
I would love to see this problem cleared up, it makes life very frustrating when I cant see what I'm doing in my bank and or the guild bank I own. I have tried other bag addons and this is the one I love and hate to have to use arkinvatory or the like.

**Comment by reflexwolf** [comment] 2018-02-24 18:33
ok, I have found if I load just Bagnon it works fine, so started slowly loading my other addons and I have found one that causes this problem to happen. it is Farmit2 and I see it hasn't been updated in quite a bit. so away it goes for now till next update happens. I hope this helps

**Comment by Eviloverlord1989** [comment] 2018-02-24 18:51
I don't have Farmit2 so that's not the actual cause.

**Comment by reflexwolf** [comment] 2018-02-24 18:55
it cleared it up for me but I didn't think it was the only cause of it, but could give the code wonks an idea of what is causing it to go nuts.

**Comment by AlexL1118** [comment] 2018-02-24 21:59
I also don't use Farmit2.
But what probably is giving idea - v7.3.2 of Bagnon works correctly.
Reflexwolf, could you try to return that Farmit2 back with Bagnon v7.3.2 and see if it helps?

**Comment by reflexwolf** [comment] 2018-02-24 22:55
*big sigh* so after hours of testing I have loaded farmit and it works again now :) I didn't know there was a new update to bagnon out, I was still using 7.3.11 thank you for the great work AlexL1118 :)

**Comment by AlexL1118** [comment] 2018-02-25 02:06
Reflexwolf, it began working again not because of new version. It began to work because of the reason which I have mentioned earlier: "...reload UI to toggle its reproducibility...". Since you could not load or unload Farmit2 without reloading UI, you got what you got: it became to work again, most probably without relation to Farmit2, just because you reloaded UI. And most probably it will stop working again, sooner or later (unless the issue will be fixed, or unless you return to Bagnon v7.3.2).

As for me - I actually suspect that "LibItemCache" (library that comes as part of Bagnon) is the reason of the problem, because the malfunctioning associates for me with "too cached" data, which forces its old non-updated status. This library changed its version from LibItemCache v1.1 in Bagnon v7.3.2 to LibItemCache v2.0 in Bagnon v7.3.3 and higher.
But I have no proofs.

**Comment by cryptaro** [comment] 2018-02-25 03:12
I had the same problem when using bagnon with an other addon called Dominos. Without, bagnon work.

**Comment by Dohram** [comment] 2018-03-10 20:03
Same , seems to clear up sometimes on a reload

**Comment by AlexL1118** [comment] 2018-03-30 11:58
Well, since I don't see any reaction or advancement, I have to set this addon to "Ignore updates" mode in Curse/Twitch, and stay with v7.3.2.

**Comment by jriggz** [comment] 2018-04-26 21:01
This issue persists. It tends to work fine the first time I open the bank, but subsequent use seems to always cause the issue.

It's not a game-breaker, but it sure is annoying, especially when you'd trying to clean your overstuffed bank.

**Comment by AlexL1118** [comment] 2018-07-25 01:57
And predictably the same problem exists in v8.0.0.

**Closed** 2023-09-12 15:44 UTC
Labels: :bug: bug
