### ISSUE TITLE
this is still happening bagnon wont even open

### ISSUE THREAD

**Issue by Creepshow1168** [Jaliborc/Bagnon#1524] opened 2022-11-28 02:56 UTC
Message: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
Time: Sun Nov 27 20:53:17 2022
Count: 1
Stack: ...erface/AddOns/Bagnon/common/Wildpants/api/events.lua:91: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:91: in function `UpdateSize'
[string "@Interface/AddOns/Bagnon/common/Wildpants/api/events.lua"]:33: in function `?'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...ommon/Wildpants/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...nts/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Bagnon/common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../common/Wildpants/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:587: in function `CombatLog_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1484: in function <Interface/FrameXML/UIParent.lua:1362>

Locals: <none>

**Comment by dartraiden** [comment] 2022-11-28 09:43
And this is still a duplicate of https://github.com/tullamods/Bagnon/issues/1491

**Closed** 2022-11-29 13:11 UTC
