### ISSUE TITLE
Cannot use items with latest update

### ISSUE THREAD

**Issue by Danderfluff** [Jaliborc/Bagnon#1582] opened 2022-12-10 09:00 UTC
The latest update has blocked the function to use items in your bag. Like making the Obsidian Keys etc.

**Comment by KonstantinosKoubetsos** [comment] 2022-12-10 09:04
I can't even open my bags without some sort of error

**Comment by Blackrayn** [comment] 2022-12-10 11:29
I can confirm the op. I'm no longer allowed to use consumables or Knowledge Point items directly from the bags. Have to move them to an action bar and use. This just started happening after I updated Bagnon last night.

**Comment by zdhar** [comment] 2022-12-10 11:30
its not bagnon himself but bagnon item level

**Comment by AldursApprentice** [comment] 2022-12-10 11:30
I'm also having trouble with USE items in my bag. I receive this msg: :: "Bagnon has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI." A simple solution (until the issue can be fixed): Click and drag the item to an open slot on one of your bars, then right click to USE. If, after use, a greyed-out icon is still on your bar, simply click, drag, and remove it. Hope this helps.

**Comment by skarpethinn** [comment] 2022-12-10 11:56
i also cannot use any item in my inventory that requires a right-click action to proceed;  I receive this msg: "Bagnon has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI."

**Comment by kasiopec** [comment] 2022-12-10 13:32
+1

**Comment by jwilliam87** [comment] 2022-12-10 14:47
I was blocked from using a Blacksmith's Writ.

**Comment by vril14** [comment] 2022-12-10 20:22
Same problem. Trying to use those DF items that give +1 profession skill.

**Comment by vril14** [comment] 2022-12-10 20:22
Date: 2022-12-10 21:21:34
ID: 23
Error occured in: AddOn: Bagnon
Count: 1
Message: Error: AddOn Bagnon attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: UseContainerItem()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1409: ContainerFrameItemButton_OnClick()
   [string "@Interface/FrameXML/ContainerFrame.lua"]:1461:
      Interface/FrameXML/ContainerFrame.lua:1448
   [string "=[C]"]: ?
Locals:
None

**Comment by Onahail** [comment] 2022-12-11 03:55
Can't interact with items in bag. Unable to disenchant items for example.

**Comment by layzsmurf** [comment] 2022-12-11 09:52
#1579 might be the cause of all of this.

**Comment by bravetothebone** [comment] 2022-12-11 11:34
I noticed the same with Awakened reagents - can't transform with the addon on :/

**Comment by layzsmurf** [comment] 2022-12-11 11:50
the problem is taint - certain functionality is only allowed for Blizzard code within certain context  - e.g. combat.

If Addon code tries to do functions that the game believes to breach thos rules it will bock it. Unfortunately the detection is not foolproof. In this case a default code got tainted so any normal addon like Bagmon using it gets blocked even though it is "normal" use. (I hope i kinda got it right).

**Comment by cleybsonol** [comment] 2022-12-11 16:50
rollback people!

**Comment by Ghostamoose** [comment] 2022-12-12 07:22
Should be fixed in the newest version.

**Closed** 2022-12-12 12:40 UTC
