### ISSUE TITLE
Bagnon seems to have been abandoned

### ISSUE THREAD

**Issue by vladdeh** [Jaliborc/Bagnon#1659] opened 2023-04-28 21:50 UTC
No updates since january and the addon has been broken for a long time now

**Comment by Rezy942** [comment] 2023-04-29 07:14
Who cares? The donation button as well as cringe asmongold clip is up, that should be enough!!!
Why you need it to work anyway?

**Comment by Senappi** [comment] 2023-05-03 14:53
> Author is the same guy that made PetTracker. 

Same author also makes Scrap which was updated recently. People who make addons does so for free you can't complain, give the guys some time and stop whining.

**Comment by Rezy942** [comment] 2023-05-03 15:00
> > Author is the same guy that made PetTracker.
> 
> Same author also makes Scrap which was updated recently. People who make addons does so for free you can't complain, give the guys some time and stop whining.

Donation buttons takes your point and throws it in the garbage.
If that goes away, i will have nothing but praise. But i will still ask someone to take over the project.
Having so many people use it and rely on it just to abandon it without possibility of passing it to someone else who cares is kind of a d*** move.
Sorry not sorry.

**Comment by Senappi** [comment] 2023-05-03 19:53
> Donation buttons takes your point and throws it in the garbage.

Like hell it does. It's optional to donate, not an obligation.  
The way I see it, you just complain a lot and don't contribute anything. It's people with an attitude like yours that gets many addon authors to just stop supporting their addon.

**Comment by Rezy942** [comment] 2023-05-03 20:25
> > Donation buttons takes your point and throws it in the garbage.
> 
> Like hell it does. It's optional to donate, not an obligation. The way I see it, you just complain a lot and don't contribute anything. It's people with an attitude like yours that gets many addon authors to just stop supporting their addon.

Your face is so far up the author's ass its not even funny.
I do contribute with bug reports and feature requests / suggestions. My time is a contribution along with many others who report for years while getting ignored entirely.
You are at level 100 of fanboy, congratulations. Reply back when you enter the real world.

**Comment by theswede007** [comment] 2023-05-04 01:04
> > > Donation buttons takes your point and throws it in the garbage.
> > 
> > 
> > Like hell it does. It's optional to donate, not an obligation. The way I see it, you just complain a lot and don't contribute anything. It's people with an attitude like yours that gets many addon authors to just stop supporting their addon.
> 
> Your face is so far up the author's ass its not even funny. I do contribute with bug reports and feature requests / suggestions. My time is a contribution along with many others who report for years while getting ignored entirely. You are at level 100 of fanboy, congratulations. Reply back when you enter the real world.

Your head is so far up your own ass if you think posting feature requests and suggestions and bug reports is a valuable contribuition.  It's also laughable that telling the person, who called you a selfish &%^#@, that they have their head up the author's ass.  It's clowns like you who drive authors away and keeps people like me from giving you the fixes when the addons break.

**Comment by Rezy942** [comment] 2023-05-04 02:07
Authors that pop a donation button soon as their addon is out*.
You clowns act like hes doing it out of the goodness of his heart.
Extreme case of fanboy-ism.
Addon is in a shit state and the author gives no sh*t. Cry me a river over opinions you dont like.
When he takes off the donation button (because his addon is currently sh*t), then i will change my stance.
As soon as money is involved - you cant expect everyone to kiss ass like you do.

**Comment by billzilla2000** [comment] 2023-05-04 20:09
For now, the addon does seem to be (at least for now) abandoned. No update or news from the dev(s). 

Whatever else anyone wants to express - posture, toss out insulting and largely performative obfuscation on behalf of the dev, I for one had been using Bagnon for years and bailed months ago when it became clear there was too much work to get it functional. Too many other alternatives that work as well or better and get regularly updated. It's as simple as that, regardless of 'who owes people this or that'. 

The truth is, nobody forced this dev to volunteer their time to create bagnon - and nobody is forcing people to pay - or forcing dev to keep developing it. I'd say once you do contribute something that rises to such significance as bagnon has to a community, that yes you do 'owe' at least a word or update in terms of your intentions - but that's life. You can't force people to be considerate and some developers get burned out or angry and bail without a word.

I will say that the (if it's not the dev themselves) the aggro fanboy defensive shilling is not a good look... And it will be interesting to see if this comment gets deleted like the other user's comments.

**Comment by jcadduono** [comment] 2023-05-04 21:17
Hi, unfortunately since this addon does not contain a license it would be assumed All Rights Reserved, so I cannot publicly share an updated version of Bagnon, however feel free to DM me on Discord @ jcadduono#6384 and I will send you a zip of Bagnon for 10.1.0 with all of the known errors fixed, as well as a "boa" search keyword to allow for easier finding of things you can send between alts. You can use this until Jaliborc gets the time to update Bagnon himself. I will continue to privately maintain my own version of Bagnon with every patch as I prefer to use it over whatever other options are out there.

**Comment by Rezy942** [comment] 2023-05-04 22:08
Both Bagnon and PetTracker are outstanding addons, both of which are abandoned and all creativity ended years ago.
The problem is addon author is reluctant to give rights to anyone else. As long as that donation button is up - why would he?
Hopefully he comes back but i doubt it. As Ive said before there are many alternatives out there like LiteBag. They deserve to get some Bagnon users.

**Comment by jcadduono** [comment] 2023-05-05 16:07
> > Hi, unfortunately since this addon does not contain a license it would be assumed All Rights Reserved, so I cannot publicly share an updated version of Bagnon, however feel free to DM me (NOT friend request) on Discord @ jcadduono#6384 and I will send you a zip of Bagnon for 10.1.0 with all of the known errors fixed, as well as a "boa" search keyword to allow for easier finding of things you can send between alts. You can use this until Jaliborc gets the time to update Bagnon himself. I will continue to privately maintain my own version of Bagnon with every patch as I prefer to use it over whatever other options are out there.
> 
> Thank you! I tried sending you a DM on Discord, but it wouldn't let me since we aren't on any shared servers, so I had to send a friend request. 

Hmm, okay, try resending request if that doesn't work email jc@adduono.com

**Comment by jcadduono** [comment] 2023-05-05 18:32
No need to ask anymore, Jaliborc has updated Bagnon for 10.1.

**Comment by billzilla2000** [comment] 2023-05-05 18:36
I just updated it and immediately am getting 'something is causing a lot of lua errors' message.

**Comment by Rezy942** [comment] 2023-05-05 21:26
> No need to ask anymore, Jaliborc has updated Bagnon for 10.1.

Unfortunately that update reflects how much effort and passion is being put into this project.
Nothing but errors and incompatibility bugs for me and other guild mates.
Dumping this addon and installing alternatives until I see some actual effort put into this & PetTracker.
If that happens, i will gladly donate (AGAIN).

**Comment by jcadduono** [comment] 2023-05-05 21:29
Works fine for me, if you are having issues you should enable scriptErrors `/console scriptErrors 1` then do whatever triggers an issue and copy and paste the error in an issue report.

**Comment by Rezy942** [comment] 2023-05-05 21:54
> Works fine for me, if you are having issues you should enable scriptErrors `/console scriptErrors 1` then do whatever triggers an issue and copy and paste the error in an issue report. Understand that addon developers aren't running the same combination of addons as you, so it's hard to know that a problem even exists if you have an incompatibility between multiple addons. To me it sounds like you may have another addon that is using the same libraries as Bagnon but is out of date so the old libraries may be loading or the old addons might be incompatible with Bagnon's newer libraries.

You may be right. Either way, going through the same thing patch after patch is getting old. I disabled Bagnon and tried both LiteBag and Inventorian. BOTH are working flawlessly. It is just not worth the effort, especially if the author does not take 8 seconds to respond to an issue or acknowledge it's even being worked on. Thank you for trying to help btw.

**Comment by billzilla2000** [comment] 2023-05-05 21:59
I don't mind patches as long as it's supported. I just wish Adibags had a way to disable the auto-sorting (your items are in a different spot every damn time you open the bags)... THAT dev openly refuses to consider such a thing.

**Closed** 2023-05-15 09:55 UTC
